services:
  # Data server service - serves raw data files
  industrialenergy_data:
    image: industrialenergy_data
    build: data/.
    volumes:
      - ./data:/app/data/
    ports:
      - 3010:3010 # Map port 3010 on the host to port 3010 in the container
    environment:
      - TZ=America/Los_Angeles

  # Dashboard application service - runs the Plotly Dash app
  industrialenergy_dashboard:
    image: industrialenergy_dashboard
    build: .
    volumes:
      - ./data:/app/data/
      - ./dashboard_app:/app/dashboard_app
    ports:
      - 3009:3009  # Map port 3009 on the host to port 3009 in the container
    environment:
      - PYTHONPATH=/app
      - DATA_SOURCE=${DATA_SOURCE:-local} # Default to "local" if the variable is not set in .en
      - DATA_SERVER_URL=http://industrialenergy_data:3010/  # URL of the container that serves data files
      - TZ=America/Los_Angeles
    depends_on:
      - "industrialenergy_data"