services:
  # Data server service - serves raw data files
  industrialenergy_data:
    image: industrialenergy_data
    build: data/.
    volumes:
      - ./data:/app/data/
    ports:
      - 3010:3010
    environment:
      - TZ=America/Los_Angeles

  # Data-pipeline service - runs the scripts to generate an integrated dataset
  industrialenergy_datapipeline:
    image: industrialenergy_datapipeline
    build:
      context: .
      dockerfile: Dockerfile.pipeline
    volumes:
      - ./tools/data_pipeline:/app/tools/data_pipeline
      - ./data:/app/data/ 
    environment:
      - PYTHONPATH=/app
      - DATA_SERVER_URL=http://industrialenergy_data:3010/
      - TZ=America/Los_Angeles
    depends_on:
      - "industrialenergy_data"

  # Dashboard application service - runs the Plotly Dash app
  industrialenergy_dashboard:
    image: industrialenergy_dashboard
    build: .
    volumes:
      - ./data:/app/data/
      - ./tools/data_pipeline:/app/tools/data_pipeline
      - ./dashboard_app:/app/dashboard_app
    ports:
      - 3009:3009
    environment:
      - PYTHONPATH=/app
      - DATA_SERVER_URL=http://industrialenergy_data:3010/  # URL of the container that serves data files
      - TZ=America/Los_Angeles
      - DASH_BASE_PATHNAME=${DASH_BASE_PATHNAME:-/}
      - DATA_DIR=${DATA_DIR:-/app/data/final}
    depends_on:
      - "industrialenergy_data"
