name: industrialenergy
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - dash=2.18.2
  - dash-core-components
  - dash-html-components
  - dash-table
  - dash-bootstrap-components=1.7.1
  - pandas=1.5.3
  - numpy=1.23.5
  - plotly=5.10.0
  - scikit-learn=1.1.3
  - pyjanitor
  - flask>=3.0.0
  - werkzeug>=3.0.0
  - jupyter-dash
  - openpyxl
  - boto3
  - s3fs
  - python-dotenv
  - pyyaml
  - matplotlib
  - openpyxl
